Update skypy notebook
lenstronomy/lenstronomy-tutorials pull request #7
Opened 2022-08-15 22:13 UTC by Vikramb1

2022-08-15 22:25 UTC, sibirrer commented on Notebooks/Simulations/skypy_lenstronomy.ipynb
>       "name": "stdout",
<p>Can you update the versions of SkyPy and lenstronomy for this notebook, and also add your name to the Authors ;)</p><p> </p><p>Can you also add a link to the SkyPy examples?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/7/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-08-15 22:25 UTC, sibirrer commented on Notebooks/Simulations/skypy_lenstronomy.ipynb
>       "name": "stdout",
<p>I spotted a typo 'th g,r,i'...</p><p> </p><p>Perhaps we can add some more links to the SimulationAPI classes</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/7/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2022-08-15 22:25 UTC, sibirrer commented on Notebooks/Simulations/skypy_lenstronomy.ipynb
>       "name": "stdout",
<pre class="ql-syntax" spellcheck="false">Line #29.            ax.imshow(img, aspect='equal', origin='lower')
</pre><p>One thing that I generally wonder is whether we can get more colorful pictures showing more colors from blue, green over yellow to red</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/7/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2022-08-15 22:27 UTC, sibirrer requested changes
Looks great!
I added some further suggestions to improve the notebook documentation. One main point is also whether you understand what is happening there and if not, you should ping me to add further documentation.

2022-08-16 04:07 UTC, Vikramb1 commented
> Looks great! I added some further suggestions to improve the notebook documentation. One main point is also whether you understand what is happening there and if not, you should ping me to add further documentation.

I think I understand all of it because of the work I had done using the simAPI notebook. I have updates the pr with the changes you requested. Please let me know if there is anything else you want me to add/modify!

2022-08-16 16:14 UTC, sibirrer approved these changes
Looks all great!
I look into the colors. There might be a bug how things get handled as lens and source seem to have the same colors

2022-08-16 16:14 UTC, merged